### ISSUE TITLE
Two errors, Error while using in regular folder, see error code below

### ISSUE THREAD

**Issue by Username23453** [flathub/io.gitlab.adhami3310.Converter#20]
I am using ZorinOS(ubuntu based)
When i try to drag & drop a jpg file from a regular folder:
"Conversion failed.
Result code: 1
Output: magick: unable to open image '/home/username123/Downloads/_334651167_164522319351962_8214800137230508080_n.jpg': No such file or directory @ error/blob.c/OpenBlob/3570."

And 2nd error is when i drag & drop an image from my "GNOME Online Account" synced google drive folder,
it gets stuck on loading.

**Comment by adhami3310** [comment]
This is the repo for the manifest, please report your issue to https://gitlab.com/adhami3310/Converter/-/issues
